package com.kea;

import java.util.ArrayList;
import java.util.Scanner;

public class Main {
    public static void PrintBy(int postnummer, ArrayList<PostInfo> list) {
        for (int i = 0; i < list.size(); i++) {
            if (postnummer == list.get(i).Postnummer)
                System.out.println(list.get(i).toString());
        }
    }
    
    public static void printPostnummer(String by, ArrayList<PostInfo> list) {
        for (int i = 0; i < list.size(); i++) {
            String normalizedInput = by.trim();
            String normalizedOutput = list.get(i).ByNavn.trim();

            if (normalizedInput.equals(normalizedOutput))
                System.out.println(list.get(i).Postnummer);
        }
    }

    public static void main(String[] args) {
        // write your code here

    System.out.print("hola");

        ArrayList<PostInfo> list = new ArrayList<>();
        list.add(new PostInfo(1061, "København K	"));
        list.add(new PostInfo(1062, "København K	"));
        list.add(new PostInfo(1063, "København K	"));
        list.add(new PostInfo(1064, "	København K	"));
        list.add(new PostInfo(1065, "	København K	"));
        list.add(new PostInfo(1066, "	København K	"));
        list.add(new PostInfo(1067, "	København K	"));
        list.add(new PostInfo(1068, "	København K	"));
        list.add(new PostInfo(1069, "	København K	"));
        list.add(new PostInfo(1070, "	København K	"));
        list.add(new PostInfo(1071, "	København K	"));
        list.add(new PostInfo(1072, "	København K	"));
        list.add(new PostInfo(1073, "	København K	"));
        list.add(new PostInfo(1074, "	København K	"));
        list.add(new PostInfo(1092, "	København K	"));
        list.add(new PostInfo(1093, "	København K	"));
        list.add(new PostInfo(1095, "	København K	"));
        list.add(new PostInfo(1098, "	København K	"));
        list.add(new PostInfo(1100, "	København K	"));
        list.add(new PostInfo(1101, "	København K	"));
        list.add(new PostInfo(1102, "	København K	"));
        list.add(new PostInfo(1103, "	København K	"));
        list.add(new PostInfo(1104, "	København K	"));
        list.add(new PostInfo(1105, "	København K	"));
        list.add(new PostInfo(1106, "	København K	"));
        list.add(new PostInfo(1107, "	København K	"));
        list.add(new PostInfo(1110, "	København K	"));
        list.add(new PostInfo(1111, "	København K	"));
        list.add(new PostInfo(1112, "	København K	"));
        list.add(new PostInfo(1113, "	København K	"));
        list.add(new PostInfo(1114, "	København K	"));
        list.add(new PostInfo(1115, "	København K	"));
        list.add(new PostInfo(1116, "	København K	"));
        list.add(new PostInfo(1117, "	København K	"));
        list.add(new PostInfo(1118, "	København K	"));
        list.add(new PostInfo(1119, "	København K	"));
        list.add(new PostInfo(1120, "	København K	"));
        list.add(new PostInfo(1121, "	København K	"));
        list.add(new PostInfo(1122, "	København K	"));
        list.add(new PostInfo(1123, "	København K	"));
        list.add(new PostInfo(1124, "	København K	"));
        list.add(new PostInfo(1125, "	København K	"));
        list.add(new PostInfo(1126, "	København K	"));
        list.add(new PostInfo(1127, "	København K	"));
        list.add(new PostInfo(1128, "	København K	"));
        list.add(new PostInfo(1129, "	København K	"));
        list.add(new PostInfo(1130, "	København K	"));
        list.add(new PostInfo(1131, "	København K	"));
        list.add(new PostInfo(1140, "	København K	"));
        list.add(new PostInfo(1147, "	København K	"));
        list.add(new PostInfo(1148, "	København K	"));
        list.add(new PostInfo(1150, "	København K	"));
        list.add(new PostInfo(1151, "	København K	"));
        list.add(new PostInfo(1152, "	København K	"));
        list.add(new PostInfo(1153, "	København K	"));
        list.add(new PostInfo(1154, "	København K	"));
        list.add(new PostInfo(1155, "	København K	"));
        list.add(new PostInfo(1156, "	København K	"));
        list.add(new PostInfo(1157, "	København K	"));
        list.add(new PostInfo(1158, "	København K	"));
        list.add(new PostInfo(1159, "	København K	"));
        list.add(new PostInfo(1160, "	København K	"));
        list.add(new PostInfo(1161, "	København K	"));
        list.add(new PostInfo(1162, "	København K	"));
        list.add(new PostInfo(1164, "	København K	"));
        list.add(new PostInfo(1165, "	København K	"));
        list.add(new PostInfo(1166, "	København K	"));
        list.add(new PostInfo(1167, "	København K	"));
        list.add(new PostInfo(1168, "	København K	"));
        list.add(new PostInfo(1169, "	København K	"));
        list.add(new PostInfo(1170, "	København K	"));
        list.add(new PostInfo(1171, "	København K	"));
        list.add(new PostInfo(1172, "	København K	"));
        list.add(new PostInfo(1173, "	København K	"));
        list.add(new PostInfo(1174, "	København K	"));
        list.add(new PostInfo(1175, "	København K	"));
        list.add(new PostInfo(1200, "	København K	"));
        list.add(new PostInfo(1201, "	København K	"));
        list.add(new PostInfo(1202, "	København K	"));
        list.add(new PostInfo(1203, "	København K	"));
        list.add(new PostInfo(1204, "	København K	"));
        list.add(new PostInfo(1205, "	København K	"));
        list.add(new PostInfo(1206, "	København K	"));
        list.add(new PostInfo(1207, "	København K	"));
        list.add(new PostInfo(1208, "	København K	"));
        list.add(new PostInfo(1209, "	København K	"));
        list.add(new PostInfo(1210, "	København K	"));
        list.add(new PostInfo(1211, "	København K	"));
        list.add(new PostInfo(1213, "	København K	"));
        list.add(new PostInfo(1214, "	København K	"));
        list.add(new PostInfo(1215, "	København K	"));
        list.add(new PostInfo(1216, "	København K	"));
        list.add(new PostInfo(1217, "	København K	"));
        list.add(new PostInfo(1218, "	København K	"));
        list.add(new PostInfo(1219, "	København K	"));
        list.add(new PostInfo(1220, "	København K	"));
        list.add(new PostInfo(1221, "	København K	"));
        list.add(new PostInfo(1240, "	København K	"));
        list.add(new PostInfo(1250, "	København K	"));
        list.add(new PostInfo(1251, "	København K	"));
        list.add(new PostInfo(1253, "	København K	"));
        list.add(new PostInfo(1254, "	København K	"));
        list.add(new PostInfo(1255, "	København K	"));
        list.add(new PostInfo(1256, "	København K	"));
        list.add(new PostInfo(1257, "	København K	"));
        list.add(new PostInfo(1259, "	København K	"));
        list.add(new PostInfo(1260, "	København K	"));
        list.add(new PostInfo(1261, "	København K	"));
        list.add(new PostInfo(1263, "	København K	"));
        list.add(new PostInfo(1264, "	København K	"));
        list.add(new PostInfo(1265, "	København K	"));
        list.add(new PostInfo(1266, "	København K	"));
        list.add(new PostInfo(1267, "	København K	"));
        list.add(new PostInfo(1268, "	København K	"));
        list.add(new PostInfo(1270, "	København K	"));
        list.add(new PostInfo(1271, "	København K	"));
        list.add(new PostInfo(1291, "	København K	"));
        list.add(new PostInfo(1300, "	København K	"));
        list.add(new PostInfo(1301, "	København K	"));
        list.add(new PostInfo(1302, "	København K	"));
        list.add(new PostInfo(1303, "	København K	"));
        list.add(new PostInfo(1304, "	København K	"));
        list.add(new PostInfo(1306, "	København K	"));
        list.add(new PostInfo(1307, "	København K	"));
        list.add(new PostInfo(1308, "	København K	"));
        list.add(new PostInfo(1309, "	København K	"));
        list.add(new PostInfo(1310, "	København K	"));
        list.add(new PostInfo(1311, "	København K	"));
        list.add(new PostInfo(1312, "	København K	"));
        list.add(new PostInfo(1313, "	København K	"));
        list.add(new PostInfo(1314, "	København K	"));
        list.add(new PostInfo(1315, "	København K	"));
        list.add(new PostInfo(1316, "	København K	"));
        list.add(new PostInfo(1317, "	København K	"));
        list.add(new PostInfo(1318, "	København K	"));
        list.add(new PostInfo(1319, "	København K	"));
        list.add(new PostInfo(1320, "	København K	"));
        list.add(new PostInfo(1321, "	København K	"));
        list.add(new PostInfo(1322, "	København K	"));
        list.add(new PostInfo(1323, "	København K	"));
        list.add(new PostInfo(1324, "	København K	"));
        list.add(new PostInfo(1325, "	København K	"));
        list.add(new PostInfo(1326, "	København K	"));
        list.add(new PostInfo(1327, "	København K	"));
        list.add(new PostInfo(1328, "	København K	"));
        list.add(new PostInfo(1329, "	København K	"));
        list.add(new PostInfo(1350, "	København K	"));
        list.add(new PostInfo(1352, "	København K	"));
        list.add(new PostInfo(1353, "	København K	"));
        list.add(new PostInfo(1354, "	København K	"));
        list.add(new PostInfo(1355, "	København K	"));
        list.add(new PostInfo(1356, "	København K	"));
        list.add(new PostInfo(1357, "	København K	"));
        list.add(new PostInfo(1358, "	København K	"));
        list.add(new PostInfo(1359, "	København K	"));
        list.add(new PostInfo(1360, "	København K	"));
        list.add(new PostInfo(1361, "	København K	"));
        list.add(new PostInfo(1362, "	København K	"));
        list.add(new PostInfo(1363, "	København K	"));
        list.add(new PostInfo(1364, "	København K	"));
        list.add(new PostInfo(1365, "	København K	"));
        list.add(new PostInfo(1366, "	København K	"));
        list.add(new PostInfo(1367, "	København K	"));
        list.add(new PostInfo(1368, "	København K	"));
        list.add(new PostInfo(1369, "	København K	"));
        list.add(new PostInfo(1370, "	København K	"));
        list.add(new PostInfo(1371, "	København K	"));
        list.add(new PostInfo(1400, "	København K	"));
        list.add(new PostInfo(1401, "	København K	"));
        list.add(new PostInfo(1402, "	København K	"));
        list.add(new PostInfo(1403, "	København K	"));
        list.add(new PostInfo(1406, "	København K	"));
        list.add(new PostInfo(1407, "	København K	"));
        list.add(new PostInfo(1408, "	København K	"));
        list.add(new PostInfo(1409, "	København K	"));
        list.add(new PostInfo(1410, "	København K	"));
        list.add(new PostInfo(1411, "	København K	"));
        list.add(new PostInfo(1412, "	København K	"));
        list.add(new PostInfo(1413, "	København K	"));
        list.add(new PostInfo(1414, "	København K	"));
        list.add(new PostInfo(1415, "	København K	"));
        list.add(new PostInfo(1416, "	København K	"));
        list.add(new PostInfo(1417, "	København K	"));
        list.add(new PostInfo(1418, "	København K	"));
        list.add(new PostInfo(1419, "	København K	"));
        list.add(new PostInfo(1420, "	København K	"));
        list.add(new PostInfo(1421, "	København K	"));
        list.add(new PostInfo(1422, "	København K	"));
        list.add(new PostInfo(1423, "	København K	"));
        list.add(new PostInfo(1424, "	København K	"));
        list.add(new PostInfo(1425, "	København K	"));
        list.add(new PostInfo(1426, "	København K	"));
        list.add(new PostInfo(1427, "	København K	"));
        list.add(new PostInfo(1428, "	København K	"));
        list.add(new PostInfo(1429, "	København K	"));
        list.add(new PostInfo(1430, "	København K	"));
        list.add(new PostInfo(1431, "	København K	"));
        list.add(new PostInfo(1432, "	København K	"));
        list.add(new PostInfo(1433, "	København K	"));
        list.add(new PostInfo(1434, "	København K	"));
        list.add(new PostInfo(1435, "	København K	"));
        list.add(new PostInfo(1436, "	København K	"));
        list.add(new PostInfo(1437, "	København K	"));
        list.add(new PostInfo(1438, "	København K	"));
        list.add(new PostInfo(1439, "	København K	"));
        list.add(new PostInfo(1440, "	København K	"));
        list.add(new PostInfo(1441, "	København K	"));
        list.add(new PostInfo(1448, "	København K	"));
        list.add(new PostInfo(1450, "	København K	"));
        list.add(new PostInfo(1451, "	København K	"));
        list.add(new PostInfo(1452, "	København K	"));
        list.add(new PostInfo(1453, "	København K	"));
        list.add(new PostInfo(1454, "	København K	"));
        list.add(new PostInfo(1455, "	København K	"));
        list.add(new PostInfo(1456, "	København K	"));
        list.add(new PostInfo(1457, "	København K	"));
        list.add(new PostInfo(1458, "	København K	"));
        list.add(new PostInfo(1459, "	København K	"));
        list.add(new PostInfo(1460, "	København K	"));
        list.add(new PostInfo(1462, "	København K	"));
        list.add(new PostInfo(1463, "	København K	"));
        list.add(new PostInfo(1464, "	København K	"));
        list.add(new PostInfo(1466, "	København K	"));
        list.add(new PostInfo(1467, "	København K	"));
        list.add(new PostInfo(1468, "	København K	"));
        list.add(new PostInfo(1470, "	København K	"));
        list.add(new PostInfo(1471, "	København K	"));
        list.add(new PostInfo(1472, "	København K	"));
        list.add(new PostInfo(1500, "	København V	"));
        list.add(new PostInfo(1513, "	Centraltastning	"));
        list.add(new PostInfo(1532, "	København V	"));
        list.add(new PostInfo(1533, "	København V	"));
        list.add(new PostInfo(1550, "	København V	"));
        list.add(new PostInfo(1551, "	København V	"));
        list.add(new PostInfo(1552, "	København V	"));
        list.add(new PostInfo(1553, "	København V	"));
        list.add(new PostInfo(1554, "	København V	"));
        list.add(new PostInfo(1555, "	København V	"));
        list.add(new PostInfo(1556, "	København V	"));
        list.add(new PostInfo(1557, "	København V	"));
        list.add(new PostInfo(1558, "	København V	"));
        list.add(new PostInfo(1559, "	København V	"));
        list.add(new PostInfo(1560, "	København V	"));
        list.add(new PostInfo(1561, "	København V	"));
        list.add(new PostInfo(1562, "	København V	"));
        list.add(new PostInfo(1563, "	København V	"));
        list.add(new PostInfo(1564, "	København V	"));
        list.add(new PostInfo(1566, "	København V	"));
        list.add(new PostInfo(1567, "	København V	"));
        list.add(new PostInfo(1568, "	København V	"));
        list.add(new PostInfo(1569, "	København V	"));
        list.add(new PostInfo(1570, "	København V	"));
        list.add(new PostInfo(1571, "	København V	"));
        list.add(new PostInfo(1572, "	København V	"));
        list.add(new PostInfo(1573, "	København V	"));
        list.add(new PostInfo(1574, "	København V	"));
        list.add(new PostInfo(1575, "	København V	"));
        list.add(new PostInfo(1576, "	København V	"));
        list.add(new PostInfo(1577, "	København V	"));
        list.add(new PostInfo(1592, "	København V	"));
        list.add(new PostInfo(1599, "	København V	"));
        list.add(new PostInfo(1600, "	København V	"));
        list.add(new PostInfo(1601, "	København V	"));
        list.add(new PostInfo(1602, "	København V	"));
        list.add(new PostInfo(1603, "	København V	"));
        list.add(new PostInfo(1604, "	København V	"));
        list.add(new PostInfo(1606, "	København V	"));
        list.add(new PostInfo(1607, "	København V	"));
        list.add(new PostInfo(1608, "	København V	"));
        list.add(new PostInfo(1609, "	København V	"));
        list.add(new PostInfo(1610, "	København V	"));
        list.add(new PostInfo(1611, "	København V	"));
        list.add(new PostInfo(1612, "	København V	"));
        list.add(new PostInfo(1613, "	København V	"));
        list.add(new PostInfo(1614, "	København V	"));
        list.add(new PostInfo(1615, "	København V	"));
        list.add(new PostInfo(1616, "	København V	"));
        list.add(new PostInfo(1617, "	København V	"));
        list.add(new PostInfo(1618, "	København V	"));
        list.add(new PostInfo(1619, "	København V	"));
        list.add(new PostInfo(1620, "	København V	"));
        list.add(new PostInfo(1621, "	København V	"));
        list.add(new PostInfo(1622, "	København V	"));
        list.add(new PostInfo(1623, "	København V	"));
        list.add(new PostInfo(1624, "	København V	"));
        list.add(new PostInfo(1630, "	København V	"));
        list.add(new PostInfo(1631, "	København V	"));
        list.add(new PostInfo(1632, "	København V	"));
        list.add(new PostInfo(1633, "	København V	"));
        list.add(new PostInfo(1634, "	København V	"));
        list.add(new PostInfo(1635, "	København V	"));
        list.add(new PostInfo(1650, "	København V	"));
        list.add(new PostInfo(1651, "	København V	"));
        list.add(new PostInfo(1652, "	København V	"));
        list.add(new PostInfo(1653, "	København V	"));
        list.add(new PostInfo(1654, "	København V	"));
        list.add(new PostInfo(1655, "	København V	"));
        list.add(new PostInfo(1656, "	København V	"));
        list.add(new PostInfo(1657, "	København V	"));
        list.add(new PostInfo(1658, "	København V	"));
        list.add(new PostInfo(1659, "	København V	"));
        list.add(new PostInfo(1660, "	København V	"));
        list.add(new PostInfo(1661, "	København V	"));
        list.add(new PostInfo(1662, "	København V	"));
        list.add(new PostInfo(1663, "	København V	"));
        list.add(new PostInfo(1664, "	København V	"));
        list.add(new PostInfo(1665, "	København V	"));
        list.add(new PostInfo(1666, "	København V	"));
        list.add(new PostInfo(1667, "	København V	"));
        list.add(new PostInfo(1668, "	København V	"));
        list.add(new PostInfo(1669, "	København V	"));
        list.add(new PostInfo(1670, "	København V	"));
        list.add(new PostInfo(1671, "	København V	"));
        list.add(new PostInfo(1672, "	København V	"));
        list.add(new PostInfo(1673, "	København V	"));
        list.add(new PostInfo(1674, "	København V	"));
        list.add(new PostInfo(1675, "	København V	"));
        list.add(new PostInfo(1676, "	København V	"));
        list.add(new PostInfo(1677, "	København V	"));
        list.add(new PostInfo(1699, "	København V	"));
        list.add(new PostInfo(1700, "	København V	"));
        list.add(new PostInfo(1701, "	København V	"));
        list.add(new PostInfo(1702, "	København V	"));
        list.add(new PostInfo(1703, "	København V	"));
        list.add(new PostInfo(1704, "	København V	"));
        list.add(new PostInfo(1705, "	København V	"));
        list.add(new PostInfo(1706, "	København V	"));
        list.add(new PostInfo(1707, "	København V	"));
        list.add(new PostInfo(1708, "	København V	"));
        list.add(new PostInfo(1709, "	København V	"));
        list.add(new PostInfo(1710, "	København V	"));
        list.add(new PostInfo(1711, "	København V	"));
        list.add(new PostInfo(1712, "	København V	"));
        list.add(new PostInfo(1714, "	København V	"));
        list.add(new PostInfo(1715, "	København V	"));
        list.add(new PostInfo(1716, "	København V	"));
        list.add(new PostInfo(1717, "	København V	"));
        list.add(new PostInfo(1718, "	København V	"));
        list.add(new PostInfo(1719, "	København V	"));
        list.add(new PostInfo(1720, "	København V	"));
        list.add(new PostInfo(1721, "	København V	"));
        list.add(new PostInfo(1722, "	København V	"));
        list.add(new PostInfo(1723, "	København V	"));
        list.add(new PostInfo(1724, "	København V	"));
        list.add(new PostInfo(1725, "	København V	"));
        list.add(new PostInfo(1726, "	København V	"));
        list.add(new PostInfo(1727, "	København V	"));
        list.add(new PostInfo(1728, "	København V	"));
        list.add(new PostInfo(1729, "	København V	"));
        list.add(new PostInfo(1730, "	København V	"));
        list.add(new PostInfo(1731, "	København V	"));
        list.add(new PostInfo(1732, "	København V	"));
        list.add(new PostInfo(1733, "	København V	"));
        list.add(new PostInfo(1734, "	København V	"));
        list.add(new PostInfo(1735, "	København V	"));
        list.add(new PostInfo(1736, "	København V	"));
        list.add(new PostInfo(1737, "	København V	"));
        list.add(new PostInfo(1738, "	København V	"));
        list.add(new PostInfo(1739, "	København V	"));
        list.add(new PostInfo(1749, "	København V	"));
        list.add(new PostInfo(1750, "	København V	"));
        list.add(new PostInfo(1751, "	København V	"));
        list.add(new PostInfo(1752, "	København V	"));
        list.add(new PostInfo(1753, "	København V	"));
        list.add(new PostInfo(1754, "	København V	"));
        list.add(new PostInfo(1755, "	København V	"));
        list.add(new PostInfo(1756, "	København V	"));
        list.add(new PostInfo(1757, "	København V	"));
        list.add(new PostInfo(1758, "	København V	"));
        list.add(new PostInfo(1759, "	København V	"));
        list.add(new PostInfo(1760, "	København V	"));
        list.add(new PostInfo(1761, "	København V	"));
        list.add(new PostInfo(1762, "	København V	"));
        list.add(new PostInfo(1763, "	København V	"));
        list.add(new PostInfo(1764, "	København V	"));
        list.add(new PostInfo(1765, "	København V	"));
        list.add(new PostInfo(1766, "	København V	"));
        list.add(new PostInfo(1770, "	København V	"));
        list.add(new PostInfo(1771, "	København V	"));
        list.add(new PostInfo(1772, "	København V	"));
        list.add(new PostInfo(1773, "	København V	"));
        list.add(new PostInfo(1774, "	København V	"));
        list.add(new PostInfo(1775, "	København V	"));
        list.add(new PostInfo(1777, "	København V	"));
        list.add(new PostInfo(1780, "	København V	"));
        list.add(new PostInfo(1785, "	København V	"));
        list.add(new PostInfo(1786, "	København V	"));
        list.add(new PostInfo(1787, "	København V	"));
        list.add(new PostInfo(1790, "	København V	"));
        list.add(new PostInfo(1799, "	København V	"));
        list.add(new PostInfo(1800, "	Frederiksberg C	"));
        list.add(new PostInfo(1801, "	Frederiksberg C	"));
        list.add(new PostInfo(1802, "	Frederiksberg C	"));
        list.add(new PostInfo(1803, "	Frederiksberg C	"));
        list.add(new PostInfo(1804, "	Frederiksberg C	"));
        list.add(new PostInfo(1805, "	Frederiksberg C	"));
        list.add(new PostInfo(1806, "	Frederiksberg C	"));
        list.add(new PostInfo(1807, "	Frederiksberg C	"));
        list.add(new PostInfo(1808, "	Frederiksberg C	"));
        list.add(new PostInfo(1809, "	Frederiksberg C	"));
        list.add(new PostInfo(1810, "	Frederiksberg C	"));
        list.add(new PostInfo(1811, "	Frederiksberg C	"));
        list.add(new PostInfo(1812, "	Frederiksberg C	"));
        list.add(new PostInfo(1813, "	Frederiksberg C	"));
        list.add(new PostInfo(1814, "	Frederiksberg C	"));
        list.add(new PostInfo(1815, "	Frederiksberg C	"));
        list.add(new PostInfo(1816, "	Frederiksberg C	"));
        list.add(new PostInfo(1817, "	Frederiksberg C	"));
        list.add(new PostInfo(1818, "	Frederiksberg C	"));
        list.add(new PostInfo(1819, "	Frederiksberg C	"));
        list.add(new PostInfo(1820, "	Frederiksberg C	"));
        list.add(new PostInfo(1822, "	Frederiksberg C	"));
        list.add(new PostInfo(1823, "	Frederiksberg C	"));
        list.add(new PostInfo(1824, "	Frederiksberg C	"));
        list.add(new PostInfo(1825, "	Frederiksberg C	"));
        list.add(new PostInfo(1826, "	Frederiksberg C	"));
        list.add(new PostInfo(1827, "	Frederiksberg C	"));
        list.add(new PostInfo(1828, "	Frederiksberg C	"));
        list.add(new PostInfo(1829, "	Frederiksberg C	"));
        list.add(new PostInfo(1850, "	Frederiksberg C	"));
        list.add(new PostInfo(1851, "	Frederiksberg C	"));
        list.add(new PostInfo(1852, "	Frederiksberg C	"));
        list.add(new PostInfo(1853, "	Frederiksberg C	"));
        list.add(new PostInfo(1854, "	Frederiksberg C	"));
        list.add(new PostInfo(1855, "	Frederiksberg C	"));
        list.add(new PostInfo(1856, "	Frederiksberg C	"));
        list.add(new PostInfo(1857, "	Frederiksberg C	"));
        list.add(new PostInfo(1860, "	Frederiksberg C	"));
        list.add(new PostInfo(1861, "	Frederiksberg C	"));
        list.add(new PostInfo(1862, "	Frederiksberg C	"));
        list.add(new PostInfo(1863, "	Frederiksberg C	"));
        list.add(new PostInfo(1864, "	Frederiksberg C	"));
        list.add(new PostInfo(1865, "	Frederiksberg C	"));
        list.add(new PostInfo(1866, "	Frederiksberg C	"));
        list.add(new PostInfo(1867, "	Frederiksberg C	"));
        list.add(new PostInfo(1868, "	Frederiksberg C	"));
        list.add(new PostInfo(1870, "	Frederiksberg C	"));
        list.add(new PostInfo(1871, "	Frederiksberg C	"));
        list.add(new PostInfo(1872, "	Frederiksberg C	"));
        list.add(new PostInfo(1873, "	Frederiksberg C	"));
        list.add(new PostInfo(1874, "	Frederiksberg C	"));
        list.add(new PostInfo(1875, "	Frederiksberg C	"));
        list.add(new PostInfo(1876, "	Frederiksberg C	"));
        list.add(new PostInfo(1877, "	Frederiksberg C	"));
        list.add(new PostInfo(1878, "	Frederiksberg C	"));
        list.add(new PostInfo(1879, "	Frederiksberg C	"));
        list.add(new PostInfo(1900, "	Frederiksberg C	"));
        list.add(new PostInfo(1901, "	Frederiksberg C	"));
        list.add(new PostInfo(1902, "	Frederiksberg C	"));
        list.add(new PostInfo(1903, "	Frederiksberg C	"));
        list.add(new PostInfo(1904, "	Frederiksberg C	"));
        list.add(new PostInfo(1905, "	Frederiksberg C	"));
        list.add(new PostInfo(1906, "	Frederiksberg C	"));
        list.add(new PostInfo(1908, "	Frederiksberg C	"));
        list.add(new PostInfo(1909, "	Frederiksberg C	"));
        list.add(new PostInfo(1910, "	Frederiksberg C	"));
        list.add(new PostInfo(1911, "	Frederiksberg C	"));
        list.add(new PostInfo(1912, "	Frederiksberg C	"));
        list.add(new PostInfo(1913, "	Frederiksberg C	"));
        list.add(new PostInfo(1914, "	Frederiksberg C	"));
        list.add(new PostInfo(1915, "	Frederiksberg C	"));
        list.add(new PostInfo(1916, "	Frederiksberg C	"));
        list.add(new PostInfo(1917, "	Frederiksberg C	"));
        list.add(new PostInfo(1920, "	Frederiksberg C	"));
        list.add(new PostInfo(1921, "	Frederiksberg C	"));
        list.add(new PostInfo(1922, "	Frederiksberg C	"));
        list.add(new PostInfo(1923, "	Frederiksberg C	"));
        list.add(new PostInfo(1924, "	Frederiksberg C	"));
        list.add(new PostInfo(1925, "	Frederiksberg C	"));
        list.add(new PostInfo(1926, "	Frederiksberg C	"));
        list.add(new PostInfo(1927, "	Frederiksberg C	"));
        list.add(new PostInfo(1928, "	Frederiksberg C	"));
        list.add(new PostInfo(1950, "	Frederiksberg C	"));
        list.add(new PostInfo(1951, "	Frederiksberg C	"));
        list.add(new PostInfo(1952, "	Frederiksberg C	"));
        list.add(new PostInfo(1953, "	Frederiksberg C	"));
        list.add(new PostInfo(1954, "	Frederiksberg C	"));
        list.add(new PostInfo(1955, "	Frederiksberg C	"));
        list.add(new PostInfo(1956, "	Frederiksberg C	"));
        list.add(new PostInfo(1957, "	Frederiksberg C	"));
        list.add(new PostInfo(1958, "	Frederiksberg C	"));
        list.add(new PostInfo(1959, "	Frederiksberg C	"));
        list.add(new PostInfo(1960, "	Frederiksberg C	"));
        list.add(new PostInfo(1961, "	Frederiksberg C	"));
        list.add(new PostInfo(1962, "	Frederiksberg C	"));
        list.add(new PostInfo(1963, "	Frederiksberg C	"));
        list.add(new PostInfo(1964, "	Frederiksberg C	"));
        list.add(new PostInfo(1965, "	Frederiksberg C	"));
        list.add(new PostInfo(1966, "	Frederiksberg C	"));
        list.add(new PostInfo(1967, "	Frederiksberg C	"));
        list.add(new PostInfo(1970, "	Frederiksberg C	"));
        list.add(new PostInfo(1971, "	Frederiksberg C	"));
        list.add(new PostInfo(1972, "	Frederiksberg C	"));
        list.add(new PostInfo(1973, "	Frederiksberg C	"));
        list.add(new PostInfo(1974, "	Frederiksberg C	"));
        list.add(new PostInfo(2000, "	Frederiksberg	"));
        list.add(new PostInfo(2100, "	København Ø	"));
        list.add(new PostInfo(2150, "	Nordhavn	"));
        list.add(new PostInfo(2200, "	København N	"));
        list.add(new PostInfo(2300, "	København S	"));
        list.add(new PostInfo(2400, "	København NV	"));
        list.add(new PostInfo(2450, "	København SV	"));
        list.add(new PostInfo(2500, "	Valby	"));
        list.add(new PostInfo(2600, "	Glostrup	"));
        list.add(new PostInfo(2605, "	Brøndby	"));
        list.add(new PostInfo(2610, "	Rødovre	"));
        list.add(new PostInfo(2620, "	Albertslund	"));
        list.add(new PostInfo(2625, "	Vallensbæk	"));
        list.add(new PostInfo(2630, "	Taastrup	"));
        list.add(new PostInfo(2635, "	Ishøj	"));
        list.add(new PostInfo(2640, "	Hedehusene	"));
        list.add(new PostInfo(2650, "	Hvidovre	"));
        list.add(new PostInfo(2660, "	Brøndby Strand	"));
        list.add(new PostInfo(2665, "	Vallensbæk Strand	"));
        list.add(new PostInfo(2670, "	Greve	"));
        list.add(new PostInfo(2680, "	Solrød Strand	"));
        list.add(new PostInfo(2690, "	Karlslunde	"));
        list.add(new PostInfo(2700, "	Brønshøj	"));
        list.add(new PostInfo(2720, "	Vanløse	"));
        list.add(new PostInfo(2730, "	Herlev	"));
        list.add(new PostInfo(2740, "	Skovlunde	"));
        list.add(new PostInfo(2750, "	Ballerup	"));
        list.add(new PostInfo(2760, "	Måløv	"));
        list.add(new PostInfo(2765, "	Smørum	"));
        list.add(new PostInfo(2770, "	Kastrup	"));
        list.add(new PostInfo(2791, "	Dragør	"));
        list.add(new PostInfo(2800, "	Kongens Lyngby	"));
        list.add(new PostInfo(2820, "	Gentofte	"));
        list.add(new PostInfo(2830, "	Virum	"));
        list.add(new PostInfo(2840, "	Holte	"));
        list.add(new PostInfo(2850, "	Nærum	"));
        list.add(new PostInfo(2860, "	Søborg	"));
        list.add(new PostInfo(2870, "	Dyssegård	"));
        list.add(new PostInfo(2880, "	Bagsværd	"));
        list.add(new PostInfo(2900, "	Hellerup	"));
        list.add(new PostInfo(2920, "	Charlottenlund	"));
        list.add(new PostInfo(2930, "	Klampenborg	"));
        list.add(new PostInfo(2942, "	Skodsborg	"));
        list.add(new PostInfo(2950, "	Vedbæk	"));
        list.add(new PostInfo(2960, "	Rungsted Kyst	"));
        list.add(new PostInfo(2970, "	Hørsholm	"));
        list.add(new PostInfo(2980, "	Kokkedal	"));
        list.add(new PostInfo(2990, "	Nivå	"));
        list.add(new PostInfo(3000, "	Helsingør	"));
        list.add(new PostInfo(3050, "	Humlebæk	"));
        list.add(new PostInfo(3060, "	Espergærde	"));
        list.add(new PostInfo(3070, "	Snekkersten	"));
        list.add(new PostInfo(3080, "	Tikøb	"));
        list.add(new PostInfo(3100, "	Hornbæk	"));
        list.add(new PostInfo(3120, "	Dronningmølle	"));
        list.add(new PostInfo(3140, "	Ålsgårde	"));
        list.add(new PostInfo(3150, "	Hellebæk	"));
        list.add(new PostInfo(3200, "	Helsinge	"));
        list.add(new PostInfo(3210, "	Vejby	"));
        list.add(new PostInfo(3220, "	Tisvildeleje	"));
        list.add(new PostInfo(3230, "	Græsted	"));
        list.add(new PostInfo(3250, "	Gilleleje	"));
        list.add(new PostInfo(3300, "	Frederiksværk	"));
        list.add(new PostInfo(3310, "Ølsted"));
        list.add(new PostInfo(3320, "	Skævinge	"));
        list.add(new PostInfo(3330, "	Gørløse	"));
        list.add(new PostInfo(3360, "	Liseleje	"));
        list.add(new PostInfo(3370, "	Melby	"));
        list.add(new PostInfo(3390, "	Hundested	"));
        list.add(new PostInfo(3400, "	Hillerød	"));
        list.add(new PostInfo(3450, "	Allerød	"));
        list.add(new PostInfo(3460, "	Birkerød	"));
        list.add(new PostInfo(3480, "	Fredensborg	"));
        list.add(new PostInfo(3490, "	Kvistgård	"));
        list.add(new PostInfo(3500, "	Værløse	"));
        list.add(new PostInfo(3520, "	Farum	"));
        list.add(new PostInfo(3540, "	Lynge	"));
        list.add(new PostInfo(3550, "	Slangerup	"));
        list.add(new PostInfo(3600, "	Frederikssund	"));
        list.add(new PostInfo(3630, "	Jægerspris	"));
        list.add(new PostInfo(3650, "	Ølstykke	"));
        list.add(new PostInfo(3660, "	Stenløse	"));
        list.add(new PostInfo(3670, "	Veksø Sjælland	"));
        list.add(new PostInfo(3700, "	Rønne	"));
        list.add(new PostInfo(3720, "	Aakirkeby	"));
        list.add(new PostInfo(3730, "	Nexø	"));
        list.add(new PostInfo(3740, "	Svaneke	"));
        list.add(new PostInfo(3751, "	Østermarie	"));
        list.add(new PostInfo(3760, "	Gudhjem	"));
        list.add(new PostInfo(3770, "	Allinge	"));
        list.add(new PostInfo(3782, "	Klemensker	"));
        list.add(new PostInfo(3790, "	Hasle	"));
        list.add(new PostInfo(4000, "	Roskilde	"));
        list.add(new PostInfo(4030, "	Tune	"));
        list.add(new PostInfo(4040, "	Jyllinge	"));
        list.add(new PostInfo(4050, "	Skibby	"));
        list.add(new PostInfo(4060, "	Kirke Såby	"));
        list.add(new PostInfo(4070, "	Kirke Hyllinge	"));
        list.add(new PostInfo(4100, "	Ringsted	"));
        list.add(new PostInfo(4130, "	Viby Sjælland	"));
        list.add(new PostInfo(4140, "	Borup	"));
        list.add(new PostInfo(4160, "	Herlufmagle	"));
        list.add(new PostInfo(4171, "	Glumsø	"));
        list.add(new PostInfo(4173, "	Fjenneslev	"));
        list.add(new PostInfo(4174, "	Jystrup Midtsj	"));
        list.add(new PostInfo(4180, "	Sorø	"));
        list.add(new PostInfo(4190, "	Munke Bjergby	"));
        list.add(new PostInfo(4200, "	Slagelse	"));
        list.add(new PostInfo(4220, "	Korsør	"));
        list.add(new PostInfo(4230, "	Skælskør	"));
        list.add(new PostInfo(4241, "	Vemmelev	"));
        list.add(new PostInfo(4242, "	Boeslunde	"));
        list.add(new PostInfo(4243, "	Rude	"));
        list.add(new PostInfo(4250, "	Fuglebjerg	"));
        list.add(new PostInfo(4261, "	Dalmose	"));
        list.add(new PostInfo(4262, "	Sandved	"));
        list.add(new PostInfo(4270, "	Høng	"));
        list.add(new PostInfo(4281, "	Gørlev	"));
        list.add(new PostInfo(4291, "	Ruds Vedby	"));
        list.add(new PostInfo(4293, "	Dianalund	"));
        list.add(new PostInfo(4295, "	Stenlille	"));
        list.add(new PostInfo(4296, "	Nyrup	"));
        list.add(new PostInfo(4300, "	Holbæk	"));
        list.add(new PostInfo(4320, "	Lejre	"));
        list.add(new PostInfo(4330, "	Hvalsø	"));
        list.add(new PostInfo(4340, "	Tølløse	"));
        list.add(new PostInfo(4350, "	Ugerløse	"));
        list.add(new PostInfo(4360, "	Kirke Eskilstrup	"));
        list.add(new PostInfo(4370, "	Store Merløse	"));
        list.add(new PostInfo(4390, "	Vipperød	"));
        list.add(new PostInfo(4400, "	Kalundborg	"));
        list.add(new PostInfo(4420, "	Regstrup	"));
        list.add(new PostInfo(4440, "	Mørkøv	"));
        list.add(new PostInfo(4450, "	Jyderup	"));
        list.add(new PostInfo(4460, "	Snertinge	"));
        list.add(new PostInfo(4470, "	Svebølle	"));
        list.add(new PostInfo(4480, "	Store Fuglede	"));
        list.add(new PostInfo(4490, "	Jerslev Sjælland	"));
        list.add(new PostInfo(4500, "	Nykøbing Sj	"));
        list.add(new PostInfo(4520, "	Svinninge	"));
        list.add(new PostInfo(4532, "	Gislinge	"));
        list.add(new PostInfo(4534, "	Hørve	"));
        list.add(new PostInfo(4540, "	Fårevejle	"));
        list.add(new PostInfo(4550, "	Asnæs	"));
        list.add(new PostInfo(4560, "	Vig	"));
        list.add(new PostInfo(4571, "	Grevinge	"));
        list.add(new PostInfo(4572, "	Nørre Asmindrup	"));
        list.add(new PostInfo(4573, "	Højby	"));
        list.add(new PostInfo(4581, "	Rørvig	"));
        list.add(new PostInfo(4583, "	Sjællands Odde	"));
        list.add(new PostInfo(4591, "	Føllenslev	"));
        list.add(new PostInfo(4592, "	Sejerø	"));
        list.add(new PostInfo(4593, "	Eskebjerg	"));
        list.add(new PostInfo(4600, "	Køge	"));
        list.add(new PostInfo(4621, "	Gadstrup	"));
        list.add(new PostInfo(4622, "	Havdrup	"));
        list.add(new PostInfo(4623, "	Lille Skensved	"));
        list.add(new PostInfo(4632, "	Bjæverskov	"));
        list.add(new PostInfo(4640, "	Faxe	"));
        list.add(new PostInfo(4652, "	Hårlev	"));
        list.add(new PostInfo(4653, "	Karise	"));
        list.add(new PostInfo(4654, "	Faxe Ladeplads	"));
        list.add(new PostInfo(4660, "	Store Heddinge	"));
        list.add(new PostInfo(4671, "	Strøby	"));
        list.add(new PostInfo(4672, "	Klippinge	"));
        list.add(new PostInfo(4673, "	Rødvig Stevns	"));
        list.add(new PostInfo(4681, "	Herfølge	"));
        list.add(new PostInfo(4682, "	Tureby	"));
        list.add(new PostInfo(4683, "	Rønnede	"));
        list.add(new PostInfo(4684, "	Holmegaard	"));
        list.add(new PostInfo(4690, "	Haslev	"));
        list.add(new PostInfo(4700, "	Næstved	"));
        list.add(new PostInfo(4720, "	Præstø	"));
        list.add(new PostInfo(4733, "	Tappernøje	"));
        list.add(new PostInfo(4735, "	Mern	"));
        list.add(new PostInfo(4736, "	Karrebæksminde	"));
        list.add(new PostInfo(4750, "	Lundby	"));
        list.add(new PostInfo(4760, "	Vordingborg	"));
        list.add(new PostInfo(4771, "	Kalvehave	"));
        list.add(new PostInfo(4772, "	Langebæk	"));
        list.add(new PostInfo(4773, "	Stensved	"));
        list.add(new PostInfo(4780, "	Stege	"));
        list.add(new PostInfo(4791, "	Borre	"));
        list.add(new PostInfo(4792, "	Askeby	"));
        list.add(new PostInfo(4793, "	Bogø By	"));
        list.add(new PostInfo(4800, "	Nykøbing F	"));
        list.add(new PostInfo(4840, "	Nørre Alslev	"));
        list.add(new PostInfo(4850, "	Stubbekøbing	"));
        list.add(new PostInfo(4862, "	Guldborg	"));
        list.add(new PostInfo(4863, "	Eskilstrup	"));
        list.add(new PostInfo(4871, "	Horbelev	"));
        list.add(new PostInfo(4872, "	Idestrup	"));
        list.add(new PostInfo(4873, "	Væggerløse	"));
        list.add(new PostInfo(4874, "	Gedser	"));
        list.add(new PostInfo(4880, "	Nysted	"));
        list.add(new PostInfo(4891, "	Toreby L	"));
        list.add(new PostInfo(4892, "	Kettinge	"));
        list.add(new PostInfo(4894, "	Øster Ulslev	"));
        list.add(new PostInfo(4895, "	Errindlev	"));
        list.add(new PostInfo(4900, "	Nakskov	"));
        list.add(new PostInfo(4912, "	Harpelunde	"));
        list.add(new PostInfo(4913, "	Horslunde	"));
        list.add(new PostInfo(4920, "	Søllested	"));
        list.add(new PostInfo(4930, "	Maribo	"));
        list.add(new PostInfo(4941, "	Bandholm	"));
        list.add(new PostInfo(4943, "	Torrig L	"));
        list.add(new PostInfo(4944, "	Fejø	"));
        list.add(new PostInfo(4951, "	Nørreballe	"));
        list.add(new PostInfo(4952, "	Stokkemarke	"));
        list.add(new PostInfo(4953, "	Vesterborg	"));
        list.add(new PostInfo(4960, "	Holeby	"));
        list.add(new PostInfo(4970, "	Rødby	"));
        list.add(new PostInfo(4983, "	Dannemare	"));
        list.add(new PostInfo(4990, "	Sakskøbing	"));
        list.add(new PostInfo(5000, "	Odense C	"));
        list.add(new PostInfo(5200, "	Odense V	"));
        list.add(new PostInfo(5210, "	Odense NV	"));
        list.add(new PostInfo(5220, "	Odense SØ	"));
        list.add(new PostInfo(5230, "	Odense M	"));
        list.add(new PostInfo(5240, "	Odense NØ	"));
        list.add(new PostInfo(5250, "	Odense SV	"));
        list.add(new PostInfo(5260, "	Odense S	"));
        list.add(new PostInfo(5270, "	Odense N	"));
        list.add(new PostInfo(5290, "	Marslev	"));
        list.add(new PostInfo(5300, "	Kerteminde	"));
        list.add(new PostInfo(5320, "	Agedrup	"));
        list.add(new PostInfo(5330, "	Munkebo	"));
        list.add(new PostInfo(5350, "	Rynkeby	"));
        list.add(new PostInfo(5370, "	Mesinge	"));
        list.add(new PostInfo(5380, "	Dalby	"));
        list.add(new PostInfo(5390, "	Martofte	"));
        list.add(new PostInfo(5400, "	Bogense	"));
        list.add(new PostInfo(5450, "	Otterup	"));
        list.add(new PostInfo(5462, "	Morud	"));
        list.add(new PostInfo(5463, "	Harndrup	"));
        list.add(new PostInfo(5464, "	Brenderup Fyn	"));
        list.add(new PostInfo(5466, "	Asperup	"));
        list.add(new PostInfo(5471, "	Søndersø	"));
        list.add(new PostInfo(5474, "	Veflinge	"));
        list.add(new PostInfo(5485, "	Skamby	"));
        list.add(new PostInfo(5491, "	Blommenslyst	"));
        list.add(new PostInfo(5492, "	Vissenbjerg	"));
        list.add(new PostInfo(5500, "	Middelfart	"));
        list.add(new PostInfo(5540, "	Ullerslev	"));
        list.add(new PostInfo(5550, "	Langeskov	"));
        list.add(new PostInfo(5560, "	Aarup	"));
        list.add(new PostInfo(5580, "	Nørre Aaby	"));
        list.add(new PostInfo(5591, "	Gelsted	"));
        list.add(new PostInfo(5592, "	Ejby	"));
        list.add(new PostInfo(5600, "	Faaborg	"));
        list.add(new PostInfo(5610, "	Assens	"));
        list.add(new PostInfo(5620, "	Glamsbjerg	"));
        list.add(new PostInfo(5631, "	Ebberup	"));
        list.add(new PostInfo(5642, "	Millinge	"));
        list.add(new PostInfo(5672, "	Broby	"));
        list.add(new PostInfo(5683, "	Haarby	"));
        list.add(new PostInfo(5690, "	Tommerup	"));
        list.add(new PostInfo(5700, "	Svendborg	"));
        list.add(new PostInfo(5750, "	Ringe	"));
        list.add(new PostInfo(5762, "	Vester Skerninge	"));
        list.add(new PostInfo(5771, "	Stenstrup	"));
        list.add(new PostInfo(5772, "	Kværndrup	"));
        list.add(new PostInfo(5792, "	Årslev	"));
        list.add(new PostInfo(5800, "	Nyborg	"));
        list.add(new PostInfo(5853, "	Ørbæk	"));
        list.add(new PostInfo(5854, "	Gislev	"));
        list.add(new PostInfo(5856, "	Ryslinge	"));
        list.add(new PostInfo(5863, "	Ferritslev Fyn	"));
        list.add(new PostInfo(5871, "	Frørup	"));
        list.add(new PostInfo(5874, "	Hesselager	"));
        list.add(new PostInfo(5881, "	Skårup Fyn	"));
        list.add(new PostInfo(5882, "	Vejstrup	"));
        list.add(new PostInfo(5883, "	Oure	"));
        list.add(new PostInfo(5884, "	Gudme	"));
        list.add(new PostInfo(5892, "	Gudbjerg Sydfyn	"));
        list.add(new PostInfo(5900, "	Rudkøbing	"));
        list.add(new PostInfo(5932, "	Humble	"));
        list.add(new PostInfo(5935, "	Bagenkop	"));
        list.add(new PostInfo(5953, "	Tranekær	"));
        list.add(new PostInfo(5960, "	Marstal	"));
        list.add(new PostInfo(5970, "	Ærøskøbing	"));
        list.add(new PostInfo(5985, "	Søby Ærø	"));
        list.add(new PostInfo(6000, "	Kolding	"));
        list.add(new PostInfo(6040, "	Egtved	"));
        list.add(new PostInfo(6051, "	Almind	"));
        list.add(new PostInfo(6052, "	Viuf	"));
        list.add(new PostInfo(6064, "	Jordrup	"));
        list.add(new PostInfo(6070, "	Christiansfeld	"));
        list.add(new PostInfo(6091, "	Bjert	"));
        list.add(new PostInfo(6092, "	Sønder Stenderup	"));
        list.add(new PostInfo(6093, "	Sjølund	"));
        list.add(new PostInfo(6094, "	Hejls	"));
        list.add(new PostInfo(6100, "	Haderslev	"));
        list.add(new PostInfo(6200, "	Aabenraa	"));
        list.add(new PostInfo(6230, "	Rødekro	"));
        list.add(new PostInfo(6240, "	Løgumkloster	"));
        list.add(new PostInfo(6261, "	Bredebro	"));
        list.add(new PostInfo(6270, "	Tønder	"));
        list.add(new PostInfo(6280, "	Højer	"));
        list.add(new PostInfo(6300, "	Gråsten	"));
        list.add(new PostInfo(6310, "	Broager	"));
        list.add(new PostInfo(6320, "	Egernsund	"));
        list.add(new PostInfo(6330, "	Padborg	"));
        list.add(new PostInfo(6340, "	Kruså	"));
        list.add(new PostInfo(6360, "	Tinglev	"));
        list.add(new PostInfo(6372, "	Bylderup-Bov	"));
        list.add(new PostInfo(6392, "	Bolderslev	"));
        list.add(new PostInfo(6400, "	Sønderborg	"));
        list.add(new PostInfo(6430, "	Nordborg	"));
        list.add(new PostInfo(6440, "	Augustenborg	"));
        list.add(new PostInfo(6470, "	Sydals	"));
        list.add(new PostInfo(6500, "	Vojens	"));
        list.add(new PostInfo(6510, "	Gram	"));
        list.add(new PostInfo(6520, "	Toftlund	"));
        list.add(new PostInfo(6534, "	Agerskov	"));
        list.add(new PostInfo(6535, "	Branderup J	"));
        list.add(new PostInfo(6541, "	Bevtoft	"));
        list.add(new PostInfo(6560, "	Sommersted	"));
        list.add(new PostInfo(6580, "	Vamdrup	"));
        list.add(new PostInfo(6600, "	Vejen	"));
        list.add(new PostInfo(6621, "	Gesten	"));
        list.add(new PostInfo(6622, "	Bække	"));
        list.add(new PostInfo(6623, "	Vorbasse	"));
        list.add(new PostInfo(6630, "	Rødding	"));
        list.add(new PostInfo(6640, "	Lunderskov	"));
        list.add(new PostInfo(6650, "	Brørup	"));
        list.add(new PostInfo(6660, "	Lintrup	"));
        list.add(new PostInfo(6670, "	Holsted	"));
        list.add(new PostInfo(6682, "	Hovborg	"));
        list.add(new PostInfo(6683, "	Føvling	"));
        list.add(new PostInfo(6690, "	Gørding	"));
        list.add(new PostInfo(6700, "	Esbjerg	"));
        list.add(new PostInfo(6705, "	Esbjerg Ø	"));
        list.add(new PostInfo(6710, "	Esbjerg V	"));
        list.add(new PostInfo(6715, "	Esbjerg N	"));
        list.add(new PostInfo(6720, "	Fanø	"));
        list.add(new PostInfo(6731, "	Tjæreborg	"));
        list.add(new PostInfo(6740, "	Bramming	"));
        list.add(new PostInfo(6752, "	Glejbjerg	"));
        list.add(new PostInfo(6753, "	Agerbæk	"));
        list.add(new PostInfo(6760, "	Ribe	"));
        list.add(new PostInfo(6771, "	Gredstedbro	"));
        list.add(new PostInfo(6780, "	Skærbæk	"));
        list.add(new PostInfo(6792, "	Rømø	"));
        list.add(new PostInfo(6800, "	Varde	"));
        list.add(new PostInfo(6818, "	Årre	"));
        list.add(new PostInfo(6823, "	Ansager	"));
        list.add(new PostInfo(6830, "	Nørre Nebel	"));
        list.add(new PostInfo(6840, "	Oksbøl	"));
        list.add(new PostInfo(6851, "	Janderup Vestj	"));
        list.add(new PostInfo(6852, "	Billum	"));
        list.add(new PostInfo(6853, "	Vejers Strand	"));
        list.add(new PostInfo(6854, "	Henne	"));
        list.add(new PostInfo(6855, "	Outrup	"));
        list.add(new PostInfo(6857, "	Blåvand	"));
        list.add(new PostInfo(6862, "	Tistrup	"));
        list.add(new PostInfo(6870, "	Ølgod	"));
        list.add(new PostInfo(6880, "	Tarm	"));
        list.add(new PostInfo(6893, "	Hemmet	"));
        list.add(new PostInfo(6900, "	Skjern	"));
        list.add(new PostInfo(6920, "	Videbæk	"));
        list.add(new PostInfo(6933, "	Kibæk	"));
        list.add(new PostInfo(6940, "	Lem St	"));
        list.add(new PostInfo(6950, "	Ringkøbing	"));
        list.add(new PostInfo(6960, "	Hvide Sande	"));
        list.add(new PostInfo(6971, "	Spjald	"));
        list.add(new PostInfo(6973, "	Ørnhøj	"));
        list.add(new PostInfo(6980, "	Tim	"));
        list.add(new PostInfo(6990, "	Ulfborg	"));
        list.add(new PostInfo(7000, "	Fredericia	"));
        list.add(new PostInfo(7007, "	Fredericia	"));
        list.add(new PostInfo(7080, "	Børkop	"));
        list.add(new PostInfo(7100, "	Vejle	"));
        list.add(new PostInfo(7120, "	Vejle Øst	"));
        list.add(new PostInfo(7130, "	Juelsminde	"));
        list.add(new PostInfo(7140, "	Stouby	"));
        list.add(new PostInfo(7150, "	Barrit	"));
        list.add(new PostInfo(7160, "	Tørring	"));
        list.add(new PostInfo(7171, "	Uldum	"));
        list.add(new PostInfo(7173, "	Vonge	"));
        list.add(new PostInfo(7182, "	Bredsten	"));
        list.add(new PostInfo(7183, "	Randbøl	"));
        list.add(new PostInfo(7184, "	Vandel	"));
        list.add(new PostInfo(7190, "	Billund	"));
        list.add(new PostInfo(7200, "	Grindsted	"));
        list.add(new PostInfo(7250, "	Hejnsvig	"));
        list.add(new PostInfo(7260, "	Sønder Omme	"));
        list.add(new PostInfo(7270, "	Stakroge	"));
        list.add(new PostInfo(7280, "	Sønder Felding	"));
        list.add(new PostInfo(7300, "	Jelling	"));
        list.add(new PostInfo(7321, "	Gadbjerg	"));
        list.add(new PostInfo(7323, "	Give	"));
        list.add(new PostInfo(7330, "	Brande	"));
        list.add(new PostInfo(7361, "	Ejstrupholm	"));
        list.add(new PostInfo(7362, "	Hampen	"));
        list.add(new PostInfo(7400, "	Herning	"));
        list.add(new PostInfo(7430, "	Ikast	"));
        list.add(new PostInfo(7441, "	Bording	"));
        list.add(new PostInfo(7442, "	Engesvang	"));
        list.add(new PostInfo(7451, "	Sunds	"));
        list.add(new PostInfo(7470, "	Karup J	"));
        list.add(new PostInfo(7480, "	Vildbjerg	"));
        list.add(new PostInfo(7490, "	Aulum	"));
        list.add(new PostInfo(7500, "	Holstebro	"));
        list.add(new PostInfo(7540, "	Haderup	"));
        list.add(new PostInfo(7550, "	Sørvad	"));
        list.add(new PostInfo(7560, "	Hjerm	"));
        list.add(new PostInfo(7570, "	Vemb	"));
        list.add(new PostInfo(7600, "	Struer	"));
        list.add(new PostInfo(7620, "	Lemvig	"));
        list.add(new PostInfo(7650, "	Bøvlingbjerg	"));
        list.add(new PostInfo(7660, "	Bækmarksbro	"));
        list.add(new PostInfo(7673, "	Harboøre	"));
        list.add(new PostInfo(7680, "	Thyborøn	"));
        list.add(new PostInfo(7700, "	Thisted	"));
        list.add(new PostInfo(7730, "	Hanstholm	"));
        list.add(new PostInfo(7741, "	Frøstrup	"));
        list.add(new PostInfo(7742, "	Vesløs	"));
        list.add(new PostInfo(7752, "	Snedsted	"));
        list.add(new PostInfo(7755, "	Bedsted Thy	"));
        list.add(new PostInfo(7760, "	Hurup Thy	"));
        list.add(new PostInfo(7770, "	Vestervig	"));
        list.add(new PostInfo(7790, "	Thyholm	"));
        list.add(new PostInfo(7800, "	Skive	"));
        list.add(new PostInfo(7830, "	Vinderup	"));
        list.add(new PostInfo(7840, "	Højslev	"));
        list.add(new PostInfo(7850, "	Stoholm Jyll	"));
        list.add(new PostInfo(7860, "	Spøttrup	"));
        list.add(new PostInfo(7870, "	Roslev	"));
        list.add(new PostInfo(7884, "	Fur	"));
        list.add(new PostInfo(7900, "	Nykøbing M	"));
        list.add(new PostInfo(7950, "	Erslev	"));
        list.add(new PostInfo(7960, "	Karby	"));
        list.add(new PostInfo(7970, "	Redsted M	"));
        list.add(new PostInfo(7980, "	Vils	"));
        list.add(new PostInfo(7990, "	Øster Assels	"));
        list.add(new PostInfo(8000, "	Aarhus C	"));
        list.add(new PostInfo(8200, "	Aarhus N	"));
        list.add(new PostInfo(8210, "	Aarhus V	"));
        list.add(new PostInfo(8220, "	Brabrand	"));
        list.add(new PostInfo(8230, "	Åbyhøj	"));
        list.add(new PostInfo(8240, "	Risskov	"));
        list.add(new PostInfo(8245, "	Risskov Ø	"));
        list.add(new PostInfo(8250, "	Egå	"));
        list.add(new PostInfo(8260, "	Viby J	"));
        list.add(new PostInfo(8270, "	Højbjerg	"));
        list.add(new PostInfo(8300, "	Odder	"));
        list.add(new PostInfo(8305, "	Samsø	"));
        list.add(new PostInfo(8310, "	Tranbjerg J	"));
        list.add(new PostInfo(8320, "	Mårslet	"));
        list.add(new PostInfo(8330, "	Beder	"));
        list.add(new PostInfo(8340, "	Malling	"));
        list.add(new PostInfo(8350, "	Hundslund	"));
        list.add(new PostInfo(8355, "	Solbjerg	"));
        list.add(new PostInfo(8361, "	Hasselager	"));
        list.add(new PostInfo(8362, "	Hørning	"));
        list.add(new PostInfo(8370, "	Hadsten	"));
        list.add(new PostInfo(8380, "	Trige	"));
        list.add(new PostInfo(8381, "	Tilst	"));
        list.add(new PostInfo(8382, "	Hinnerup	"));
        list.add(new PostInfo(8400, "	Ebeltoft	"));
        list.add(new PostInfo(8410, "	Rønde	"));
        list.add(new PostInfo(8420, "	Knebel	"));
        list.add(new PostInfo(8444, "	Balle	"));
        list.add(new PostInfo(8450, "	Hammel	"));
        list.add(new PostInfo(8462, "	Harlev J	"));
        list.add(new PostInfo(8464, "	Galten	"));
        list.add(new PostInfo(8471, "	Sabro	"));
        list.add(new PostInfo(8472, "	Sporup	"));
        list.add(new PostInfo(8500, "	Grenaa	"));
        list.add(new PostInfo(8520, "	Lystrup	"));
        list.add(new PostInfo(8530, "	Hjortshøj	"));
        list.add(new PostInfo(8541, "	Skødstrup	"));
        list.add(new PostInfo(8543, "	Hornslet	"));
        list.add(new PostInfo(8544, "	Mørke	"));
        list.add(new PostInfo(8550, "	Ryomgård	"));
        list.add(new PostInfo(8560, "	Kolind	"));
        list.add(new PostInfo(8570, "	Trustrup	"));
        list.add(new PostInfo(8581, "	Nimtofte	"));
        list.add(new PostInfo(8585, "	Glesborg	"));
        list.add(new PostInfo(8586, "	Ørum Djurs	"));
        list.add(new PostInfo(8592, "	Anholt	"));
        list.add(new PostInfo(8600, "	Silkeborg	"));
        list.add(new PostInfo(8620, "	Kjellerup	"));
        list.add(new PostInfo(8632, "	Lemming	"));
        list.add(new PostInfo(8641, "	Sorring	"));
        list.add(new PostInfo(8643, "	Ans By	"));
        list.add(new PostInfo(8653, "	Them	"));
        list.add(new PostInfo(8654, "	Bryrup	"));
        list.add(new PostInfo(8660, "	Skanderborg	"));
        list.add(new PostInfo(8670, "	Låsby	"));
        list.add(new PostInfo(8680, "	Ry	"));
        list.add(new PostInfo(8700, "	Horsens	"));
        list.add(new PostInfo(8721, "	Daugård	"));
        list.add(new PostInfo(8722, "	Hedensted	"));
        list.add(new PostInfo(8723, "	Løsning	"));
        list.add(new PostInfo(8732, "	Hovedgård	"));
        list.add(new PostInfo(8740, "	Brædstrup	"));
        list.add(new PostInfo(8751, "	Gedved	"));
        list.add(new PostInfo(8752, "	Østbirk	"));
        list.add(new PostInfo(8762, "	Flemming	"));
        list.add(new PostInfo(8763, "	Rask Mølle	"));
        list.add(new PostInfo(8765, "	Klovborg	"));
        list.add(new PostInfo(8766, "	Nørre Snede	"));
        list.add(new PostInfo(8781, "	Stenderup	"));
        list.add(new PostInfo(8783, "	Hornsyld	"));
        list.add(new PostInfo(8800, "	Viborg	"));
        list.add(new PostInfo(8830, "	Tjele	"));
        list.add(new PostInfo(8831, "	Løgstrup	"));
        list.add(new PostInfo(8832, "	Skals	"));
        list.add(new PostInfo(8840, "	Rødkærsbro	"));
        list.add(new PostInfo(8850, "	Bjerringbro	"));
        list.add(new PostInfo(8860, "	Ulstrup	"));
        list.add(new PostInfo(8870, "	Langå	"));
        list.add(new PostInfo(8881, "	Thorsø	"));
        list.add(new PostInfo(8882, "	Fårvang	"));
        list.add(new PostInfo(8883, "	Gjern	"));
        list.add(new PostInfo(8900, "	Randers C	"));
        list.add(new PostInfo(8920, "	Randers NV	"));
        list.add(new PostInfo(8930, "	Randers NØ	"));
        list.add(new PostInfo(8940, "	Randers SV	"));
        list.add(new PostInfo(8950, "	Ørsted	"));
        list.add(new PostInfo(8960, "	Randers SØ	"));
        list.add(new PostInfo(8961, "	Allingåbro	"));
        list.add(new PostInfo(8963, "	Auning	"));
        list.add(new PostInfo(8970, "	Havndal	"));
        list.add(new PostInfo(8981, "	Spentrup	"));
        list.add(new PostInfo(8983, "	Gjerlev J	"));
        list.add(new PostInfo(8990, "	Fårup	"));
        list.add(new PostInfo(9000, "	Aalborg	"));
        list.add(new PostInfo(9200, "	Aalborg SV	"));
        list.add(new PostInfo(9210, "	Aalborg SØ	"));
        list.add(new PostInfo(9220, "	Aalborg Øst	"));
        list.add(new PostInfo(9230, "	Svenstrup J	"));
        list.add(new PostInfo(9240, "	Nibe	"));
        list.add(new PostInfo(9260, "	Gistrup	"));
        list.add(new PostInfo(9270, "	Klarup	"));
        list.add(new PostInfo(9280, "	Storvorde	"));
        list.add(new PostInfo(9293, "	Kongerslev	"));
        list.add(new PostInfo(9300, "	Sæby	"));
        list.add(new PostInfo(9310, "	Vodskov	"));
        list.add(new PostInfo(9320, "	Hjallerup	"));
        list.add(new PostInfo(9330, "	Dronninglund	"));
        list.add(new PostInfo(9340, "	Asaa	"));
        list.add(new PostInfo(9352, "	Dybvad	"));
        list.add(new PostInfo(9362, "	Gandrup	"));
        list.add(new PostInfo(9370, "	Hals	"));
        list.add(new PostInfo(9380, "	Vestbjerg	"));
        list.add(new PostInfo(9381, "	Sulsted	"));
        list.add(new PostInfo(9382, "	Tylstrup	"));
        list.add(new PostInfo(9400, "	Nørresundby	"));
        list.add(new PostInfo(9430, "	Vadum	"));
        list.add(new PostInfo(9440, "	Aabybro	"));
        list.add(new PostInfo(9460, "	Brovst	"));
        list.add(new PostInfo(9480, "	Løkken	"));
        list.add(new PostInfo(9490, "	Pandrup	"));
        list.add(new PostInfo(9492, "	Blokhus	"));
        list.add(new PostInfo(9493, "	Saltum	"));
        list.add(new PostInfo(9500, "	Hobro	"));
        list.add(new PostInfo(9510, "	Arden	"));
        list.add(new PostInfo(9520, "	Skørping	"));
        list.add(new PostInfo(9530, "	Støvring	"));
        list.add(new PostInfo(9541, "	Suldrup	"));
        list.add(new PostInfo(9550, "	Mariager	"));
        list.add(new PostInfo(9560, "	Hadsund	"));
        list.add(new PostInfo(9574, "	Bælum	"));
        list.add(new PostInfo(9575, "	Terndrup	"));
        list.add(new PostInfo(9600, "	Aars	"));
        list.add(new PostInfo(9610, "	Nørager	"));
        list.add(new PostInfo(9620, "	Aalestrup	"));
        list.add(new PostInfo(9631, "	Gedsted	"));
        list.add(new PostInfo(9632, "	Møldrup	"));
        list.add(new PostInfo(9640, "	Farsø	"));
        list.add(new PostInfo(9670, "	Løgstør	"));
        list.add(new PostInfo(9681, "	Ranum	"));
        list.add(new PostInfo(9690, "	Fjerritslev	"));
        list.add(new PostInfo(9700, "	Brønderslev	"));
        list.add(new PostInfo(9740, "	Jerslev J	"));
        list.add(new PostInfo(9750, "	Østervrå	"));
        list.add(new PostInfo(9760, "	Vrå	"));
        list.add(new PostInfo(9800, "	Hjørring	"));
        list.add(new PostInfo(9830, "	Tårs	"));
        list.add(new PostInfo(9850, "	Hirtshals	"));
        list.add(new PostInfo(9870, "	Sindal	"));
        list.add(new PostInfo(9881, "	Bindslev	"));
        list.add(new PostInfo(9900, "	Frederikshavn	"));
        list.add(new PostInfo(9940, "	Læsø	"));
        list.add(new PostInfo(9970, "	Strandby	"));
        list.add(new PostInfo(9981, "	Jerup	"));
        list.add(new PostInfo(9982, "	Ålbæk	"));
        list.add(new PostInfo(9990, "	Skagen	"));

        Scanner scan = new Scanner(System.in);
        System.out.print("Indtast en by: ");
        String by = scan.nextLine();
        printPostnummer(by,list);

        System.out.print("Indtast postnummer: ");
        try {
            int postnummer = scan.nextInt();
            PrintBy(postnummer, list);

        }
        catch (Exception e){
            System.out.println("Wrong input");
        }

//second try
        System.out.print("Indtast et andet postnummer: ");
       try {
            int postnummer2 = scan.nextInt();
            PrintBy(postnummer2, list);
        }
        catch (Exception e){
             System.out.println("Input mismatch");
        }




    /*  long start = System.currentTimeMillis();

        list.forEach(x ->
        {
            printPostnummer(x.ByNavn, list);
        });
   //     printPostnummer(by, list);
        long end = System.currentTimeMillis();
        long result = end - start;

        long seconds = TimeUnit.MILLISECONDS.toSeconds(result);
        System.out.println("Elapsed milliseconds: " + result);
       }
*/
    }
}


